Rayman-Sodhi/Clone-IT

- README.md
Fixed the issue #4 ( Create Readme for the Project ) .
<br>
Hey, @Rayman-Sodhi , Checkout this PR and if everything is fine , Kindly merge it . 
Thanks ...
> Fixed - #4

- LINKEDIN-CLONE/index,html
Updated the navbar of LinkedIn clone
-added new elements such as my network,jobs and notifications.
-added icons for every button
> Updated navbar linkedin clone

- index.css
hey just saw after the merge there was some problem with the header's image about it's height in the mobile view. Now it's resolved.
> fixed header's image

- index.css
have made the project boxes four in a row.
> updated project section

- index.html
One minor change, earlier it was redirecting to error 404 page when clicked on main logo at the top of home page.
> corrected link on main logo

- index.css
Added Smoother animations on:
* Navlinks
* Explore/Github links
* Projects section cards
* 'Send Message' button in the contact us form
* footer links
Fixes #64
> Added Smooth animations

- .vscode/settings.json
> deleted .vscode

- index.html
Closes #104
when a user clicks social media links on the website it redirects to a new page
> Clicking the image to open link in new tab

- index.css
- index.html
> fix: add responsiveness to projects' section

- index.html
Changing from checking with if statements to json for easier way to add
new clone url.
Closes #186 
I think `GOOGLE CLONE` is referring to the `GOOGLE SEARCH ENGINE CLONE`,so I added `GOOGLE CLONE` to open up the same page.
Adds clones that are not in the search bar filter if I did not miss any.
Also changes the way search bar is written. So people in the future will have easier time when adding new clone and url. 
image redirects to YouTube.
[![](https://i.imgur.com/vD2ecEa.png)](https://youtu.be/WI8iPJOX6DY)
> Changed how the search bar is written.

- index.html
Closes #202 
- changed divs to correct html semantic tags
- made sure lists of projects used ul and li tags
No screenshots because it's not a visible fix.
> fix: improve accessibility by updating html tags

- Grammarly(Character Counter)/index.html
- Grammarly(Character Counter)/readme.md
- Grammarly(Character Counter)/script.js
- Grammarly(Character Counter)/style.css
Closes #
- #237 
- It's a clone of Grammarly with some additional features. I have added the Character count feature into it which shows the typed and remaining characters on the screen and also here is a major feature is that we can copy Text with the button provided.
https://user-images.githubusercontent.com/77873383/161383612-fb4a8faf-4476-47ba-af35-2e6486c411af.mp4
> Grammarly(Character Counter)

- chatwoot.js
- index.css
- index.html
Closes #240 
Chatbot added in site, used chatwoot in Javascript, now you can talk with bot or me directly with that live chatbot I will give access to admin in future so she will handle all things
> Chabot created 

- Discord_App_Clone/assets/css/style.css
- Discord_App_Clone/home.html
Added padding and margins to the navbar buttons.
Closes #
Added more friends and changed font style so that it could match the real app much better.
> Better Styling

- index.css
- index.html
Button to scroll to the top added
To adjust the overlapping of chat button and top scroll button
> Added a button to scroll to the top

- index.css
> Update scroll top btn

- index.html
Closes #268 
Removed the extra footer present in the code.
> Extra footer removed

- README.md
* Grammar improvements
* Removing typos
* There are also some adjustments required in 'About' section of the GitHub repo (see the screenshot with a couple of examples below).
You can copy-paste the improved version from 'About the Clone IT' section in README.md.
* Maybe in [Add a reference(remote) to the original repository](https://github.com/Rayman-Sodhi/Clone-IT#add-a-referenceremote-to-the-original-repository) section instead of 
> ... to keep it at par with ...
use
> ... to keep up with ...
in order to avoid misunderstanding?
> Fix typos and grammar mistakes in README.md

- FACEBOOK-CLONE/fb clone/app.css
- FACEBOOK-CLONE/fb clone/index.html
Closes #285 
Included a login page for the facebook clone, further I intent to connect it to the main page via dummy login ids.
- [X ] My code follows the code style of this project.
- [X ] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.
> Login page FACEBOOK CLONE

- Wordle_Clone/index.html
- Wordle_Clone/script.js
- Wordle_Clone/style.css
Closes #239 
Added README and changed files. Wordle Clone added.
> Wordle-Clone

- index.html
Closes #257
-Missing JS code to be added
To note changes refer PR: #299
> Added JS for hamburger

- README.md
> Adding Mentor Section and link for repo contributors

- FAQ-PAGE/faq.html
- FAQ-PAGE/styles.css
- index.css
Closes #346 
Fixed the navbar and footer of FAQ page
> Navbar and Footer of FAQ page fixed

- Swiggy-clone/README.md
- Swiggy-clone/style.css
- Swiggy-clone/swiggy.html
Hey I made swiggy clone Project Which Is Very Good!
This Project is very Helpfull,
I Make This Project With the help of HTML & CSS,
The HTML & CSS Code are Available in very well mannered! & Easy to understand!
> Adding swiggy clone

- FLIPKART-CLONE/index.html
- FLIPKART-CLONE/script.js
- FLIPKART-CLONE/style.css
> Changes in flipkart clone

- zara/index.html
Add images to zara clone . there are two images which are not visible ,now i add images .
#429 issue is solved
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
> adding images to zara clone

- index.css
- index.html
Closes #422 
@gurjeetsinghvirdee, @Rayman-Sodhi, please check the PR now
> Made website changes

- index.html
Closes #439 
The description of the Wordle Game Clone is wrong . It is about wikipedia and not wordle.
> Wordle description changed

- NVIDIA_Clone/README.md
- NVIDIA_Clone/index.html
- NVIDIA_Clone/styles.css
Closes #458 
I have Added responsiveness to NVIDIA clone.
Please review my PR. @Rayman-Sodhi @gurjeetsinghvirdee 
https://user-images.githubusercontent.com/93239528/167344034-7866265f-5aec-41bc-a96e-e95a8941f125.mp4
> Added responsiveness to NVIDIA clone

- Instagram-reels-clone/index.html
- Instagram-reels-clone/style.css
> IG reels clone

- APK Mirror/index.html
- APK Mirror/style.css
> Apk Mirror

- EA Sports Facebook Page/index.html
- EA Sports Facebook Page/style.css
> EA Sports Facebook Page Clone

- zara/index.html
- zara/style.css
Closes #530 
Edited the Title card
Improved the fonts and styling
Changed and updated the background and contents to the current website.
Original site
Clone site
> Updates on ZARA's new website

- FTV/README.md
- FTV/about.html
- FTV/index.html
- FTV/script.js
- FTV/style.css
FTV files added with readme
Closes #
https://user-images.githubusercontent.com/91609324/169582325-8535ea30-00f2-4a77-a2c2-0bbf4d5535c8.mp4
> FashionTV+

- Razer clone/README.md
- Razer clone/index.html
- Razer clone/style.css
Razer Clone files added with readme
Closes #557
Razer Clone Made with HTML CSS JS
https://user-images.githubusercontent.com/91609324/169755123-8580e132-2ff1-4c8d-b273-fd528936a06b.mp4
> Razer Clone 

- PayPal UI/README.md
- PayPal UI/index.html
- PayPal UI/script.js
- PayPal UI/style.css
Closes #401 
- Added responsive PayPal UI clone  Code made with **HTML, CSS and JAVASCRIPT**
https://user-images.githubusercontent.com/77873383/170035445-539a21bb-9d13-489d-ba85-9eccfd10b3df.mp4
> Paypal UI Clone 

- Google Meet/index.html
- Google Meet/style.css
> Google Meet

- Zomato/index.html
- Zomato/styles.css
- [ ✔️] My code follows the code style of this project.
- [ ✔️] This PR does not contain plagiarized content.
- [ ✔️] The title of my pull request is a short description of the requested changes.
> zomato clone

- README.md
- Social Summer of Code (SSOC) changed into Social Summer of Code (SWOC)
- HackClub Rait Logo fixed
> Open Source Programs section typos fixed

- FAQ-PAGE/faq.html
- FAQ-PAGE/styles.css
- index.css
- index.html
Reverts Rayman-Sodhi/Clone-IT#715
> Revert "about section & faq page updated ✨"
